### ISSUE TITLE
Missing avatars that need to be added

### ISSUE THREAD

**Issue by willettk** [zooniverse/Brand#16]
So @jwbmartin is the new empress of avatars now, right?

Projects missing from this repo:

* Orchid Observers
* Measuring the ANZACs
* Chimp & See
* AnnoTate
* Science Gossip
* Higgs Hunters
* Chicago Wildlife Watch #12 
* Snapshot Supernova #14

**Comment by jwbmartin** [comment]
Do we know if these avatars have been created and they are just lost in the sea of files I've inherited because some of these projects are older so I imagine they already have avatars?

**Comment by willettk** [comment]
I've seen a crossed circle-style avatar for every project I listed up there (usually at the Twitter feed, if nowhere else). So I think they've all been created and just need to be found in the bounty of files you've inherited.

**Comment by jwbmartin** [comment]
This might help http://adobe.ly/1LkXXe3

**Comment by eatyourgreens** [comment]
I've got jpegs for a couple on the ConSciCom blog. http://conscicom.org/projects/

**Comment by willettk** [comment]
Thanks, @eatyourgreens. I think @jwbmartin found hi-res versions of most of them.

**Comment by VVH** [comment]
hey @jwbmartin and @willettk I attach AnnoTate here and Shakespeare's World, which I know Jordan has already. We also need to add in ANZACS, Old Weather Whaling if these aren't in here already. 

![avatar_shakes](https://cloud.githubusercontent.com/assets/6482891/11562908/bbf16076-99c8-11e5-8831-38ff0e2ed37e.jpg)

![avatar_annotate_150715](https://cloud.githubusercontent.com/assets/6482891/11562919/d04ed044-99c8-11e5-8ed0-e64a6244ce61.jpg)

**Comment by willettk** [comment]
Thanks, @VVH. They're added in #10 - just waiting for someone with write access to approve the commit.

**Comment by astopy** [comment]
Closed by #17
